
import os
import json
from pathlib import Path
from dotenv import load_dotenv
import fitz  # PyMuPDF
import docx
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings
from langchain.agents import tool, AgentExecutor
from langchain.schema import Document
from langchain_community.vectorstores import FAISS
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
from langchain.prompts import ChatPromptTemplate
from langchain.agents.output_parsers.openai_tools import OpenAIToolsAgentOutputParser
from langchain.agents.format_scratchpad.openai_tools import format_to_openai_tool_messages
from langchain_core.prompts import MessagesPlaceholder
from langchain.schema.messages import AIMessage

# Load environment variables
load_dotenv()

# Fetch API keys and endpoints
openai_api_key = os.getenv("OPENAI_API_KEY")
azure_endpoint = os.getenv("AZURE_ENDPOINT")

if not openai_api_key or not azure_endpoint:
    raise EnvironmentError("Missing Azure OpenAI API keys or endpoint. Please check your environment variables.")

# Initialize Azure OpenAI model
llm = AzureChatOpenAI(
    deployment_name="gpt-4o",
    model_name="gpt-4o",
    temperature=0,
    openai_api_key=openai_api_key,
    azure_endpoint=azure_endpoint,
    openai_api_type="azure",
)

@tool
def policy_inquiry(email_text: str) -> str:
    """
    Use this tool to answer questions related to company policies based on the email text (query) 
    and the attachments (context), with the query generated by the LLM.
    """
    def extract_text_from_pdf(pdf_path):
        doc = fitz.open(pdf_path)
        text = ""
        for page in doc:
            text += page.get_text()
        return text
    
    def extract_text_from_docx(docx_path):
        """Extract text from a .docx file."""
        doc = docx.Document(docx_path)
        text = "\n".join([para.text for para in doc.paragraphs])
        return text

    def extract_text_from_txt(txt_path):
        """Extract text from a .txt file."""
        with open(txt_path, 'r', encoding='utf-8') as file:
            return file.read()


    def chunk_text(text, file_name, chunk_size=1000, overlap=200):
        """
        Chunk text into smaller parts with overlap and associate metadata for source identification.
        """
        start = 0
        documents = []
        while start < len(text):
            end = start + chunk_size
            chunk = text[start:end]
            documents.append(Document(page_content=chunk, metadata={"source": file_name}))
            start += chunk_size - overlap
        return documents

    def process_policy_directory(directory_path):
        """Process .pdf, .docx, and .txt files in the policies directory."""
        all_chunks = []
        for filename in os.listdir(directory_path):
            file_path = os.path.join(directory_path, filename)
            if filename.endswith(".pdf"):
                print(f"Processing PDF: {file_path}...")
                text = extract_text_from_pdf(file_path)
            elif filename.endswith(".docx"):
                print(f"Processing DOCX: {file_path}...")
                text = extract_text_from_docx(file_path)
            elif filename.endswith(".txt"):
                print(f"Processing TXT: {file_path}...")
                text = extract_text_from_txt(file_path)
            else:
                print(f"Skipping unsupported file: {file_path}")
                continue

            # Chunk text and add to all_chunks
            chunks = chunk_text(text, file_name=filename)
            all_chunks.extend(chunks)
        return all_chunks

    def create_retriever(documents):
        embedding_function = AzureOpenAIEmbeddings(api_key=os.getenv("OPENAI_API_KEY"), azure_endpoint=os.getenv("AZURE_ENDPOINT"))
        vector_store = FAISS.from_documents(documents, embedding_function)
        return vector_store.as_retriever()

    def create_rag_chain(retriever):
        prompt_template = """You are an assistant that provides answers based on the context provided.
        Context: {context}
        Question: {input}
        """

        prompt = ChatPromptTemplate.from_template(prompt_template)
        chain = create_stuff_documents_chain(llm, prompt)
        retrieval_chain = create_retrieval_chain(retriever, chain)
        return retrieval_chain

    try:
        # Initialize RAG
        policy_directory = r"C:\Users\BHARGAVIELURI\Desktop\EmailAgent\POLICY"
        print(f"Processing policies from directory: {policy_directory}")

        policy_chunks = process_policy_directory(policy_directory)
        retriever = create_retriever(policy_chunks)
        
        # Extract text from the attachment(s) to use as context
        attachments_directory =r"C:\Users\BHARGAVIELURI\Desktop\EmailAgent\attachments"
        print(f"Processing attachments from directory: {attachments_directory}")
        
        # Check if the attachments directory exists and is not empty
        attachment_text=""
        if attachments_directory:
                attachment_text =  process_policy_directory(attachments_directory)
        else:
            print("No files found in the attachments directory.")
            
        combined_input = email_text
        if attachment_text:
            # Extract the page content (text) from each Document in the list before concatenating
            attachment_text_str = "\n".join([doc.page_content for doc in attachment_text])
            combined_input += "\n\n" + attachment_text_str
            query = f"""You are an assistant tasked with recommending a company policy based on the content provided in an email and, if available, attachments.
 
            Based on the following email content and any attachment(s), generate a detailed query to search the company's policies. If there are attachments, analyze the content and include relevant details in your query. If no attachments are provided, focus solely on the email text.
 
            Please be specific about the user's intent and the context provided in the email and/or attachments. Your goal is to recommend the best policy that addresses the query.
 
            Email Content:
            {email_text}
 
            Attachment Content:
            {attachment_text} (If no attachments are provided, leave this section empty.)
 
            Recommended Policy:"""
        else:
            print("No attachments found, using only email text.")
           
            query= f"""You are an assistant tasked with recommending a company policy based on the content provided in an email.
 
            Based solely on the email content below, generate a detailed query to search the company's policies. Be specific about the user's intent and the context provided in the email. Your goal is to recommend the best policy that addresses the query.
 
            Email Content:
            {email_text}
 
            Recommended Policy:"""
       
       
         # Generate the combined query text using LLM
        combined_query_response = llm.invoke(query)  # Pass the prompt as a string, not dict
        

        # Check if the response is a string or a dictionary with 'content'
        if isinstance(combined_query_response, str):
            combined_query = combined_query_response
        elif isinstance(combined_query_response, dict):
            if "content" in combined_query_response:
                combined_query = combined_query_response["content"]
            else:
                raise ValueError(f"Unexpected LLM response structure: {combined_query_response}")
        elif isinstance(combined_query_response, AIMessage):
            # Extract the content from AIMessage
            combined_query = combined_query_response.content
        else:
            raise ValueError(f"Unexpected response type: {type(combined_query_response)}")


        
        
        # Query RAG with the generated combined query
        rag_chain = create_rag_chain(retriever)
        response = rag_chain.invoke({"input": combined_query})

        # Retrieve documents and sources
        retrieved_docs = retriever.invoke(combined_query)
        sources = ", ".join(set(doc.metadata.get("source", "Unknown") for doc in retrieved_docs)) if retrieved_docs else "No sources found"
        
        best_doc = retrieved_docs[0] if retrieved_docs else None  # Assuming the first document is the best one

        # Get the name of the best policy (document filename)
        best_policy_name = best_doc.metadata.get("source", "Unknown") if best_doc else "No policy found"

        return {
            # "best_policy_name": best_policy_name,
            "answer": response['answer'],
            "sources": sources,
        }

        # return f"{response['answer']} (Sources: {sources})"
        # return f"Recommended Policy: {best_policy_name}\nAnswer: {response['answer']} (Sources: {sources})"


    except Exception as e:
        return f"Error processing the policy inquiry: {str(e)}"

policy_prompt = """
You are an HR assistant. You have access to a tool named `policy_inquiry`.
- When the user’s intent is a policy inquiry, always call the tool with:
  name: "policy_inquiry"
  arguments: {{
    "email_text": <the user email text>,
    "attachments": <the attachments if available>
  }}
 
After you call the tool and get the response, provide the final answer to the user.
 
Email Text:
{email_text}
 
Intent: {intent}
 
Now, start reasoning:
"""


policy_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", policy_prompt),
        ("user", "{email_text}\nIntent: {intent}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)

llm_with_tools = llm.bind_tools([policy_inquiry])

policy_agent = (
    {
        "email_text": lambda x: x["email_text"],
        "intent": lambda x: x["intent"],
        "agent_scratchpad": lambda x: format_to_openai_tool_messages(x["intermediate_steps"]),
    }
    | policy_prompt_template
    | llm_with_tools
    | OpenAIToolsAgentOutputParser()
)

agent_policy_executor = AgentExecutor(agent=policy_agent, tools=[policy_inquiry], verbose=True)